[package]
name = "roll_lang"
version = "0.1.0"
authors = ["jacob <jacobrwguenther@protonmail.com>"]
edition = "2018"
repository = "https://github.com/jacobguenther/roll_lang"

[lib]
crate-type = ["cdylib"]

[dependencies]
unicode-segmentation = "1.6.0"



[dependencies.lazy_static]
version = "1.4.0"
optional = true

[dependencies.wasm-bindgen]
version = "0.2.67"
optional = true

[dependencies.console_error_panic_hook]
version = "0.1.6"
optional = true

[dependencies.web-sys]
version = "0.3"
features = [ "Window", "Document", "HtmlDocument", "Element", "HtmlTextAreaElement", "HtmlInputElement"]
optional = true

[dependencies.js-sys]
version = "0.3.44"
optional = true

[features]
default = ["web"]

web = ["lazy_static", "wasm-bindgen", "console_error_panic_hook", "web-sys", "js-sys"]