[package]
name = "roll_lang"
version = "0.1.0"
authors = ["jacob <jacobrwguenther@protonmail.com>"]
edition = "2018"
repository = "https://github.com/jacobguenther/roll_lang"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[lib]
crate-type = ["lib"]

[dependencies]
unicode-segmentation = "1.6.0"