[package]
name = "roll_lang"
version = "0.1.0"
authors = ["jacob <jacobrwguenther@protonmail.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.65"
console_error_panic_hook = "0.1.4"
unicode-segmentation = "1.6.0"
